# Generated by Django 5.1.6 on 2025-09-16 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อที่พัก')),
                ('type', models.CharField(choices=[('hotel', 'โรงแรม'), ('resort', 'รีสอร์ท'), ('guesthouse', 'เกสต์เฮาส์'), ('homestay', 'โฮมสเตย์'), ('hostel', 'หอสเตล')], max_length=20, verbose_name='ประเภท')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('district', models.CharField(max_length=50, verbose_name='อำเภอ')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('phone', models.CharField(max_length=15, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('website', models.URLField(blank=True, verbose_name='เว็บไซต์')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคาต่อคืน (เริ่มต้น)')),
                ('total_rooms', models.IntegerField(verbose_name='จำนวนห้องทั้งหมด')),
                ('available_rooms', models.IntegerField(verbose_name='ห้องว่าง')),
                ('amenities', models.TextField(blank=True, verbose_name='สิ่งอำนวยความสะดวก')),
                ('check_in_time', models.TimeField(verbose_name='เวลาเช็คอิน')),
                ('check_out_time', models.TimeField(verbose_name='เวลาเช็คเอาท์')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนน')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้บริการ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ที่พัก',
                'verbose_name_plural': 'ที่พัก',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('accommodation', 'จองที่พัก'), ('tour_package', 'จองแพ็คเกจทัวร์')], max_length=20, verbose_name='ประเภทการจอง')),
                ('check_in_date', models.DateField(blank=True, null=True, verbose_name='วันเช็คอิน')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='วันเช็คเอาท์')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='จำนวนห้อง')),
                ('tour_date', models.DateField(blank=True, null=True, verbose_name='วันทัวร์')),
                ('adults', models.IntegerField(blank=True, null=True, verbose_name='จำนวนผู้ใหญ่')),
                ('children', models.IntegerField(default=0, verbose_name='จำนวนเด็ก')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวม')),
                ('status', models.CharField(choices=[('pending', 'รอการยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('paid', 'ชำระเงินแล้ว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('special_requests', models.TextField(blank=True, verbose_name='ความต้องการพิเศษ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accommodation', verbose_name='ที่พัก')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนน')),
                ('comment', models.TextField(verbose_name='ความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accommodation', verbose_name='ที่พัก')),
            ],
            options={
                'verbose_name': 'รีวิว',
                'verbose_name_plural': 'รีวิว',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='เบอร์โทร')),
                ('id_card', models.CharField(blank=True, max_length=13, verbose_name='เลขบัตรประชาชน')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='ผู้ติดต่อฉุกเฉิน')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='เบอร์ติดต่อฉุกเฉิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_tourist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'นักท่องเที่ยว',
                'verbose_name_plural': 'นักท่องเที่ยว',
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสถานที่')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('category', models.CharField(choices=[('temple', 'วัด/ศาสนสถาน'), ('historical', 'แหล่งโบราณคดี'), ('natural', 'แหล่งธรรมชาติ'), ('cultural', 'แหล่งวัฒนธรรม'), ('market', 'ตลาด/ของฝาก'), ('recreation', 'สันทนาการ')], max_length=20, verbose_name='หมวดหมู่')),
                ('district', models.CharField(max_length=50, verbose_name='อำเภอ')),
                ('subdistrict', models.CharField(max_length=50, verbose_name='ตำบล')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='ละติจูด')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='ลองจิจูด')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='เวลาเปิด-ปิด')),
                ('entrance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ค่าเข้าชม')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='เบอร์โทร')),
                ('website', models.URLField(blank=True, verbose_name='เว็บไซต์')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้เข้าชม')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สถานที่ท่องเที่ยว',
                'verbose_name_plural': 'สถานที่ท่องเที่ยว',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแพ็คเกจ')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('duration', models.CharField(choices=[('half_day', 'ครึ่งวัน'), ('full_day', '1 วัน'), ('2_days', '2 วัน 1 คืน'), ('3_days', '3 วัน 2 คืน'), ('custom', 'กำหนดเอง')], max_length=20, verbose_name='ระยะเวลา')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคาผู้ใหญ่')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ราคาเด็ก')),
                ('max_participants', models.IntegerField(verbose_name='จำนวนผู้เข้าร่วมสูงสุด')),
                ('included_services', models.TextField(verbose_name='บริการที่รวม')),
                ('excluded_services', models.TextField(blank=True, verbose_name='บริการที่ไม่รวม')),
                ('meeting_point', models.CharField(max_length=200, verbose_name='จุดนัดพบ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้บริการ')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attractions', models.ManyToManyField(blank=True, to='api.touristattraction', verbose_name='สถานที่ในแพ็คเกจ')),
            ],
            options={
                'verbose_name': 'แพ็คเกจทัวร์',
                'verbose_name_plural': 'แพ็คเกจทัวร์',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Placeholder',
        ),
        migrations.AddField(
            model_name='review',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tourist', verbose_name='นักท่องเที่ยว'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tourist', verbose_name='นักท่องเที่ยว'),
        ),
        migrations.AddField(
            model_name='review',
            name='attraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.touristattraction', verbose_name='สถานที่ท่องเที่ยว'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tourpackage', verbose_name='แพ็คเกจทัวร์'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tourpackage', verbose_name='แพ็คเกจทัวร์'),
        ),
    ]
