# Generated by Django 5.2.6 on 2025-09-30 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accommodation_booking_review_tourist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='กรุณากรอกหมายเลขโทรศัพท์ไทยที่ถูกต้อง เช่น 081-234-5678 หรือ +66812345678', regex='^(\\+66|0)[0-9]{8,9}$')], verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='กรุณากรอกหมายเลขโทรศัพท์ไทยที่ถูกต้อง เช่น 081-234-5678 หรือ +66812345678', regex='^(\\+66|0)[0-9]{8,9}$')], verbose_name='เบอร์ติดต่อฉุกเฉิน'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='id_card',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='เลขบัตรประชาชนต้องเป็นตัวเลข 13 หลัก', regex='^[0-9]{13}$')], verbose_name='เลขบัตรประชาชน'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='กรุณากรอกหมายเลขโทรศัพท์ไทยที่ถูกต้อง เช่น 081-234-5678 หรือ +66812345678', regex='^(\\+66|0)[0-9]{8,9}$')], verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='กรุณากรอกหมายเลขโทรศัพท์ไทยที่ถูกต้อง เช่น 081-234-5678 หรือ +66812345678', regex='^(\\+66|0)[0-9]{8,9}$')], verbose_name='เบอร์โทร'),
        ),
    ]
